[package]

name = "xinerama"
version = "0.0.1"
authors = ["Simon Wollwage"]
license = "BSD"
description = "A rust wrapper around libXinerama"

[dependencies.xlib]
git = "https://github.com/Kintaro/rust-xlib.git"

[lib]

name = "xinerama"
crate-type = ["rlib"]
